spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #测试环境
  application:
    name: microservice-cloud-dev
---
spring:
  profiles: test #开发环境
  application:
    name: microservice-cloud-test