spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: cloud-config-eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: config-eureka
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: cloud-config-eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: config-eureka